config/routes.rb
Rails.application.routes.draw do
  root "api#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups do 
    resources :links
  end
  resources :uploads, only: [:index, :new, :create, :destroy]
  resources :api
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :links

    validates :name, presence: true
    validates :grouptype, presence: true
    validates :municipality, presence: true
    validates :description, presence: false
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :group

  validates :linkname, presence: true
  validates :url, presence: true
end

app/models/upload.rb
class Upload < ActiveRecord::Base
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def index
    raw = Group.all
    @groups = raw.map { |r| {**r.as_json(except: :description), links: format_links(r.links) } }
    render json: @groups
  end

  def show
    raw = Group.find(params[:id])
    @group = format_group(raw)
    render json: @group
  end

  private
    def group_params
      params.require(:group).permit(:name, :grouptype, :municipality, :link, :description)
    end

    def format_group(group)
      return {**group.as_json, links: format_links(group.links) }
    end

    def format_links(links)
      return links.map { |l| {linkname: l.linkname, url: l.url} }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "p4ssword"
  # , except: [:index, :show]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to root_path
  end

  private
    def group_params
      params.require(:group).permit(:name, :grouptype, :municipality, :description)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "p4ssword"

    def create
    @group = Group.find(params[:group_id])
    @link = @group.links.create(link_params)
    redirect_to group_path(@group)
  end

  def destroy
    @group = Group.find(params[:group_id])
    @link = @group.links.find(params[:id])
    @link.destroy
    redirect_to group_path(@group)
  end
  
  private
    def link_params
      params.require(:link).permit(:linkname, :url)
    end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
   http_basic_authenticate_with name: "admin", password: "p4ssword"

    def index
        @groups = Group.all
        @uploads = Upload.all
    end
   def new
      @upload = Upload.new
   end
   
   def create
      @upload = Upload.new(upload_params)
      @data = JSON.parse(File.read('public' + @upload.attachment_url))
      @data["grupper"].each do |g|

         # ActiveRecord ALREADY CONTAINS GROUP
         if Group.exists?(name: g["navn"])
         group = Group.where(name: g["navn"]).first
         gd = group_data(g)
         if group.update(gd)
               puts g["navn"] + " " + "Updated!"
               add_links(g["links"], group)
         end
         # ActiveRecord DOES NOT CONTAIN GROUP
         else 
         gd = group_data(g)
         group = Group.new(gd)
            if group.save
               puts "#{group.id} #{group.name} Created!"
               add_links(g["links"], group)
            end
         end
      end
      FileUtils.rm_rf('public' + @upload.attachment_url)
      
      redirect_to uploads_path
      ## SAVE UPLOAD TO FILE##
      # if @upload.save
      #    redirect_to uploads_path, notice: "The file #{@upload.name} has been uploaded."
      # else
      #    render "new"
      # end
   end
   
   def destroy
      @upload = Upload.find(params[:id])
      @upload.destroy
      redirect_to uploads_path, notice:  "The file #{@upload.name} has been deleted."
   end
   
   private
      def upload_params
      params.require(:upload).permit(:name, :attachment)
      end      

      def group_params
      params.require(:upload).permit(:name, :municipality, :grouptype, :description)
      end

      def group_data(g)
         return {:name => g["navn"],
            :municipality => g["kommune"],
            :grouptype => g["type"],
            :description => g["beskrivelse"]
         }
      end

      def add_links(links, group)
            links.each do |l|
               name = l.kind_of?(String) ? "facebook" : l.linkname
               group.links.create({:linkname => name, :url => l})
            end
      end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @group.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :municipality %><br>
    <%= form.text_field :municipality %>
    <% @group.errors.full_messages_for(:municipality).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :grouptype %><br>
    <%= form.text_field :grouptype %>
    <% @group.errors.full_messages_for(:grouptype).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @group.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_groupheader.html.erb
<h1><strong>Navn:</strong> <%= @group.name %></h1>
<p><strong>Kommune:</strong> <%= @group.municipality %></p>
<p><strong>Type</strong> <%= @group.grouptype%></p>
<% if !@group.description.blank? %>
<p><strong>Beskrivelse:</strong> <%= @group.description%></p>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>
<%= render "groupheader", group: @group %>
<%= render "form", group: @group %><br>
<strong>Links:</strong>
<%= render @group.links %>
<h2>Add a Link:</h2>
<%= form_with model: [ @group, @group.links.build ] do |form| %>
  <p>
    <%= form.label :linkname %><br>
    <%= form.text_field :linkname %>
  </p>
  <p>
    <%= form.label :url %><br>
    <%= form.text_area :url %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<ul>
  <li><%= link_to "Delete Group", group_path(@group),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
  </li>
</ul>

app/views/groups/index.html.erb
<h1>Groups</h1>
<div>
<ul>
  <% @groups.each do |group| %>
    <li>
      <%= link_to group.name, group %>
    </li>
  <% end %>
  
</ul>
<%= link_to "New Group", new_group_path %>
<%= link_to "Upload JSON-file", uploads_path %>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<%= render "groupheader", group: @group %>
<strong>Links:</strong>
<%= render @group.links %>
<strong><%= link_to "Edit", edit_group_path(@group) %></strong>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GNFBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%
=begin%>
 <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %> 
<%
=end%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
      <div class = "container" style = "padding-top:20px;">
         <%= yield %>
      </div>
   </body>

app/views/links/_link.html.erb
  <p>
    <%= link_to link.linkname, url_for(link.url), :target => "_blank" %>
    <%= link_to 'Delete Link', [link.group, link],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
  </p>

app/views/uploads/index.html.erb
<h1>Upload</h1>
<%= link_to "New", new_upload_path %>

<h2>Group List:</h2>
  <% @groups.each do |group| %>
    <li>
      <%= link_to group.name, group %>
    </li>
  <% end %>

<h2>Uploaded Files</h2>
  <table>
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   <tbody>
      <% @uploads.each do |upload| %>
         <tr>
            <td><%= upload.name %></td>
            <td>
               <%= link_to "Download Resume", upload.attachment_url %> 
               <%
=begin%>
 <%= JSON.parse(File.open('public' + upload.attachment_url).read) %> 
<%
=end%>
            </td>
            <td><%= button_to "Delete",  upload, method: :delete, confirm: "Are you sure that you wish to delete #{upload.name}?" %></td>
         </tr>
      <% end %>
   </tbody>

app/views/uploads/new.html.erb
<% if !@upload.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @upload.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @upload, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Upload", class: "btn btn-primary" %>
   <% end %>
</div>